#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_FileType_7-Zip.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_FileType_BandiZip.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_FileType_Excel.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_FileType_IcoFX.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_FileType_M6Librarian.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_FileType_Notepad.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_FileType_PotPlayer.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_FileType_Scite4AutoHotkey.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_FileType_VirtualDriveMaster.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_FileType_Word.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_isFile.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_isMultiSel.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_isSingleSel.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_isText.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_NoTextContent.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_OnlyFile.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_OnlyFolder.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFilters\CustomFilter_OnlyWindow.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFunctions\CustomFunction_AhkChm.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFunctions\CustomFunction_getDocumentPath.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFunctions\CustomFunction_getFileManagerAddressBarText.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFunctions\CustomFunction_GroupAdd.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFunctions\CustomFunction_HDrop.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFunctions\CustomFunction_PipeRun.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFunctions\CustomFunction_RunD.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFunctions\CustomFunction_SkSub_UrlEncode.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFunctions\CustomFunction_TaskDialogEx.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFunctions\CustomFunction_TextEscaping.ahk
#include *i %A_ScriptDir%\User\Custom\CustomFunctions\CustomVar.ahk
#include *i %A_ScriptDir%\User\Custom\FileTags\DM_Custom_FileTags.ahk
#include *i %A_ScriptDir%\User\Custom\QRCode\CustomFunction_Text2QRCode.ahk
#include *i %A_ScriptDir%\User\Custom\ScreenCapture\ScreenCapture.ahk
#include *i %A_ScriptDir%\User\Custom\ShellNew\新AHK脚本.ahk
#include *i %A_ScriptDir%\User\FileTags\FileTags.ahk
#include *i %A_ScriptDir%\User\Tools\getDocumentPath.ahk
#include *i %A_ScriptDir%\User\Totalcmd\TC收藏夹.ahk
#include *i %A_ScriptDir%\User\示例\box.ahk
#include *i %A_ScriptDir%\User\示例\FileDrop.ahk
#include *i %A_ScriptDir%\User\示例\ParentDirName.ahk
#include *i %A_ScriptDir%\User\示例\ResumWin.ahk
#include *i %A_ScriptDir%\User\示例\select_value.ahk
#include *i %A_ScriptDir%\User\示例\TC_PostMsg.ahk
#include *i %A_ScriptDir%\User\示例\TestAPI.ahk
#include *i %A_ScriptDir%\User\示例\TestFunc.ahk
#include *i %A_ScriptDir%\User\示例\收藏夹示例.ahk
