notepad++:
    Gen_Save_Win := []
    vim.SetAction("<down>", "向下移动")
    vim.SetAction("<up>", "向上移动")
    vim.SetAction("<left>", "向左移动")
    vim.SetAction("<right>", "向右移动")
    vim.SetAction("<home>", "home键")
    vim.SetAction("<end>", "end键")
    vim.SetAction("<Gen_InsertMode>", "插入模式")
    vim.SetAction("<Gen_NormalMode>", "浏览模式")
    vim.SetAction("<Gen_Toggle>", "启用/禁用vim热键(Notepad++插件)")
    vim.SetAction("<Reload>", "重新加载")
    vim.SetAction("<WindowMoveDown>", "窗口移动到下方")
    vim.SetAction("<WindowMoveUp>", "窗口移动到上方")
    vim.SetAction("<WindowMoveLeft>", "窗口移动到左侧")
    vim.SetAction("<WindowMoveRight>", "窗口移动到右侧")
    vim.SetAction("<WindowMoveCenter>", "窗口移动到中间")
    vim.SetAction("<WindowMax>", "最大化窗口")
    vim.SetAction("<WindowMaxNoTitle>", "最大化窗口，并且隐藏标题栏")
    vim.SetAction("<WindowMin>", "最小化窗口")
    vim.SetAction("<WindowRestore>", "还原当前窗口")
    vim.SetAction("<FullScreen>", "全屏当前程序")
    vim.SetAction("<NextTab>", "下一个标签")
    vim.SetAction("<PrevTab>", "前一个标签")
    vim.SetAction("<CloseTab>", "关闭当前标签")
    vim.SetAction("<CloseWindow>", "关闭当前Window")
    vim.SetAction("<NewTab>", "新建标签")
    vim.SetAction("<ActivateTab1>", "激活第一个标签")
    vim.SetAction("<ActivateTab2>", "激活第二个标签")
    vim.SetAction("<ActivateTab3>", "激活第三个标签")
    vim.SetAction("<ActivateTab4>", "激活第四个标签")
    vim.SetAction("<ActivateTab5>", "激活第五个标签")
    vim.SetAction("<ActivateTab6>", "激活第六个标签")
    vim.SetAction("<ActivateTab7>", "激活第七个标签")
    vim.SetAction("<ActivateTab8>", "激活第八个标签")
    vim.SetAction("<ActivateTab9>", "激活第九个标签")
    vim.SetAction("<ActivateTab0>", "激活最后一个标签")
    vim.SetAction("<pgup>", "上一页")
    vim.SetAction("<pgdn>", "下一页")
    vim.SetAction("<enter>", "回车键")
    vim.SetAction("<space>", "空格键")
    vim.SetAction("<backspace>", "退格键")
    vim.SetAction("<Pass>", "屏蔽按键")
    vim.SetAction("<Media_Next>", "播放下一首")
    vim.SetAction("<Media_Prev>", "播放上一首")
    vim.SetAction("<Media_Play_Pause>", "播放/停止")
    vim.SetAction("<Media_Stop>", "停止播放")
    vim.SetAction("<RemoveToolTip>", "清除屏幕的ToolTip")
    vim.SetAction("<ShowHelp>", "显示所有按键帮助信息")
    vim.SetAction("<ToggleCapsLock>", "切换大小写")
    vim.SetAction("<MouseUp>", "向上移动鼠标")
    vim.SetAction("<MouseDown>", "向下移动鼠标")
    vim.SetAction("<MouseLeft>", "向左移动鼠标")
    vim.SetAction("<MouseRight>", "向右移动鼠标")
    vim.SetAction("<SearchInWeb>", "在网络搜索剪切板内容")
    vim.SetAction("<PrintScreenAndSave>", "截图并保存")
    vim.SetAction("<RunZ>", "运行 RunZ")
    vim.SetAction("<Test>", "测试")


    vim.SetWin("General", "notepad++")
    vim.SetMode("insert", "notepad++")
    vim.map("<Esc>", "<Gen_NormalMode>", "notepad++")
    vim.SetMode("normal", "notepad++")
    vim.map("i", "<Gen_InsertMode>", "notepad++")
    vim.map("0", "<0>", "notepad++")
    vim.map("1", "<1>", "notepad++")
    vim.map("2", "<2>", "notepad++")
    vim.map("3", "<3>", "notepad++")
    vim.map("4", "<4>", "notepad++")
    vim.map("5", "<5>", "notepad++")
    vim.map("6", "<6>", "notepad++")
    vim.map("7", "<7>", "notepad++")
    vim.map("8", "<8>", "notepad++")
    vim.map("9", "<9>", "notepad++")
    vim.map("k", "<up>", "notepad++")
    vim.map("j", "<down>", "notepad++")
    vim.map("k", "<up>", "notepad++")
    vim.map("h", "<left>", "notepad++")
    vim.map("l", "<right>", "notepad++")
	vim.map("gg", "<home>", "notepad++")
    vim.map("G", "<end>", "notepad++")
    vim.map("zj", "<WindowMoveDown>", "notepad++")
    vim.map("zk", "<WindowMoveUp>", "notepad++")
    vim.map("zh", "<WindowMoveLeft>", "notepad++")
    vim.map("zl", "<WindowMoveRight>", "notepad++")
    vim.map("zc", "<WindowMoveCenter>", "notepad++")
    vim.map("zf", "<fullscreen>", "notepad++")
    vim.map("zm", "<WindowMax>", "notepad++")
    vim.map("zn", "<WindowMin>", "notepad++")
    vim.map("zr", "<WindowRestore>", "notepad++")
    vim.map("t", "<NewTab>", "notepad++")
    vim.map("x", "<CloseTab>", "notepad++")
    vim.map("cc", "<CloseWindow>", "notepad++")
    vim.map("a", "<LeftTab>", "notepad++")
    vim.map("d", "<RightTab>", "notepad++")
    vim.map("w", "<wheelup2>", "notepad++")
    vim.map("s", "<wheeldown2>", "notepad++")
    vim.map("yy", "<dupLine>", "notepad++")
    vim.map("yd", "<cutLine>", "notepad++")
    vim.map("gj", "<LeftTab>", "notepad++")
    vim.map("gk", "<RightTab>", "notepad++")
    vim.map("gh", "<LeftTab>", "notepad++")
    vim.map("gl", "<RightTab>", "notepad++")

    vim.map("gf", "<Eve_GetSelected>", "notepad++")
    vim.map("gp", "<Eve_GetPath>", "notepad++")
	
    vim.map("[", "<NextTab>", "notepad++")
    vim.map("]", "<PrevTab>", "notepad++")
    vim.map("n", "<NextTab>", "notepad++")
    vim.map("p", "<PrevTab>", "notepad++")
    vim.map("g1", "<ActivateTab1>", "notepad++")
    vim.map("g2", "<ActivateTab2>", "notepad++")
    vim.map("g3", "<ActivateTab3>", "notepad++")
    vim.map("g4", "<ActivateTab4>", "notepad++")
    vim.map("g5", "<ActivateTab5>", "notepad++")
    vim.map("g6", "<ActivateTab6>", "notepad++")
    vim.map("g7", "<ActivateTab7>", "notepad++")
    vim.map("g8", "<ActivateTab8>", "notepad++")
    vim.map("g9", "<ActivateTab9>", "notepad++")
    vim.map("g0", "<ActivateTab0>", "notepad++")
    vim.BeforeActionDo("Gen_Before", "notepad++")
return
